Repository playframework/scalatestplus-play, pull requests merged in 2019-04, with the labels that each got.

#110 Update build to use sbt 1.0 (also enables mima)
  .travis.yml
  build.sbt
  docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/allbrowserspersuite/ExampleOverrideBrowsersSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/allbrowserspersuite/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/allbrowserspertest/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/mixedfixtures/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/oneapppersuite/NestedExampleComponentsSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/onebrowserpersuite/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/onebrowserpertest/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/oneserverpersuite/NestedExampleComponentsSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/playspec/ExampleSpec.scala
  docs/manual/working/scalaGuide/main/tests/code/views/html/index.scala
  module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
  module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
  module/src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
  module/src/main/scala/org/scalatestplus/play/components/OneAppPerSuiteWithComponents.scala
  module/src/main/scala/org/scalatestplus/play/components/OneAppPerTestWithComponents.scala
  module/src/main/scala/org/scalatestplus/play/components/OneServerPerSuiteWithComponents.scala
  module/src/main/scala/org/scalatestplus/play/components/OneServerPerTestWithComponents.scala
  module/src/test/scala/org/scalatestplus/play/AllBrowsersPerSuiteBehaviorSpec.scala
  module/src/test/scala/org/scalatestplus/play/AllBrowsersPerTestBehaviorSpec.scala
  module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerSuiteSpec.scala
  module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerTestSpec.scala
  module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithOneBrowserPerSuiteSpec.scala
  module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithOneBrowserPerTestSpec.scala
  module/src/test/scala/org/scalatestplus/play/OneServerPerTestComponentShutdownSpec.scala
  module/src/test/scala/org/scalatestplus/play/OneServerPerTestComponentSynchronizationSpec.scala
  module/src/test/scala/org/scalatestplus/play/TestRoute.scala
  module/src/test/scala/org/scalatestplus/play/examples/components/oneapppersuite/NestedExampleSpec.scala
  module/src/test/scala/org/scalatestplus/play/examples/components/oneserverpersuite/NestedExampleSpec.scala
  module/src/test/scala/org/scalatestplus/play/examples/guice/oneapppersuite/NestedExampleSpec.scala
  module/src/test/scala/org/scalatestplus/play/examples/guice/onebrowserpersuite/NestedExampleSpec.scala
  module/src/test/scala/org/scalatestplus/play/examples/guice/oneserverpersuite/NestedExampleSpec.scala
  project/build.properties
  project/plugins.sbt
  scripts/validateCode
  version.sbt
Labels: status:backlog

#143 Update htmlunit-driver to 2.34.0
  build.sbt
Labels: status:needs-backport

#147 Fix travis setup
  .travis.yml
  build.sbt
Labels: status:needs-backport

#158 Add snapshot repositories
  project/plugins.sbt
Labels: status:needs-backport, topic:build/tests
